### ISSUE TITLE
LAB 04 Instruction file not found

### ISSUE THREAD

**Issue by sunaynagoel** [DS4PS/cpp-529-master#14]
Hello Professor

When I click on the lab instruction for this week it gives me following error. 
![Screen Shot 2019-11-07 at 10 40 59 AM](https://user-images.githubusercontent.com/54381453/68413344-4cbf4580-014b-11ea-84f3-9a75b73cfc9c.png)

**Comment by lecy** [comment]
That was my fault! The link is fixed now.

**Comment by etbartell** [comment]
@lecy @Anthony-Howell-PhD I'm still getting the same error page:

![image](https://user-images.githubusercontent.com/54336036/68422188-89dc0580-0154-11ea-856a-d8243eeee8db.png)

**Comment by lecy** [comment]
Please refresh your page and try it now. The direct link is here:

https://ds4ps.org/cpp-529-master/labs/lab-04-instructions.html

**Comment by sunaynagoel** [comment]
Thank you. The link is working for me.
